const locationCodes = {
  "1F": "1st Floor",
  "2F": "2nd Floor",
  "AD": "Adult",
  "ADDISLL": "Adult Display, Lower Level",
  "ADDISML": "Adult Display, Main Level",
  "ADRF": "Adult Reference",
  "ADRF2F": "Adult Reference, 2nd Floor",
  "AD1F": "Adult, 1st Floor",
  "AD2F": "Adult, 2nd Floor",
  "ADLL": "Adult, Lower Level",
  "ADML": "Adult, Main Level",
  "AVOV": "Adult, Oversize",
  "ADPA": "Adult, Paperbacks",
  "ARC": "Archives",
  "APB": "Art of Picture Book",
  "ASK": "Ask Staff for Help",
  "AV": "Audiovisual",
  "AV2F": "Audiovisual, 2nd Floor",
  "AUT": "Auto Manuals",
  "BSR": "Bestsellers",
  "BC2F": "Bookclub, 2nd Floor",
  "BKMB": "Bookmobile",
  "BUBGF": "Bubbler, Ground Floor",
  "BB": "Busy Bags",
  "CH": "Children's",
  "CHCH": "Children's Chapter",
  "CHCR": "Children's Crates",
  "CHDIS": "Children's Display",
  "CHDISML": "Children's Display, Main Level",
  "CHRF": "Children's Reference",
  "CHRFLL": "Children's Reference, Lower Level",
  "CHRFML": "Children's Reference, Main Level",
  "CR": "Children's Resource Collection",
  "CHSE": "Children's Series",
  "CH1F": "Children's, 1st Floor",
  "CH2F": "Children's, 2nd Floor",
  "CHLL": "Children's, Lower Level",
  "CHML": "Children's, Main Level",
  "CHOV": "Children's, Oversize",
  "CHUL": "Children's, Upper Level",
  "CS": "Civil Service Shelves",
  "CON": "Consumer Collection",
  "CUL": "Culture",
  "DC": "Day Care Collection",
  "DE": "Desk",
  "GE": "Genealogy Room",
  "GE2F": "Genealogy Room, 2nd Floor",
  "GEN": "General Collection",
  "INT": "Intermediate",
  "KV": "Kvamme Library",
  "LT": "Literacy",
  "LT2F": "Literacy, 2nd Floor",
  "LHR": "Local History Room",
  "LHR2F": "Local History Room, 2nd Floor",
  "LL": "Lower Level",
  "LD": "Lucky Day Collection",
  "MIM": "Made in Monroe",
  "ML": "Main Level",
  "MKSP": "Makerspace",
  "MED1F": "Media Lab, 1st Floor",
  "MEM": "Memorial Room",
  "MZ": "Mezzanine",
  "MRS": "Mobile Reading Service",
  "NA": "New Adult",
  "NA1F": "New Adult, 1st Floor",
  "NA2F": "New Adult, 2nd Floor",
  "NAML": "New Adult, Main Level",
  "NAMZ": "New Adult, Mezzanine",
  "NAV": "New Audiovisual",
  "NC": "New Children's",
  "NC1F": "New Children's, 1st Floor",
  "NCLL": "New Children's, Lower Level",
  "NCML": "New Children's, Main Level",
  "NR": "New Readers",
  "NR1F": "New Readers, 1st Floor",
  "NT": "New Teen",
  "NT1F": "New Teen, 1st Floor",
  "NT2F": "New Teen, 2nd Floor",
  "NTML": "New Teen, Main Level",
  "NY": "New Young Adult",
  "NY2F": "New Young Adult, 2nd Floor",
  "NW": "Norwegian Collection",
  "OF": "Office",
  "DIS": "On Display",
  "OC": "Outreach Collection",
  "OFLOW": "Overflow",
  "OV": "Oversize",
  "OV2F": "Oversize, 2nd Floor",
  "PC": "Parenting Collection",
  "PC1F": "Parenting Collection, 1st Floor",
  "PCLL": "Parenting Collection, Lower Level",
  "PCML": "Parenting Collection, Main Level",
  "POP": "Pop Culture Collection",
  "PCPLRCPLO": "Portage County PL PLO Rotating Collection",
  "PCPLRC": "Portage County PL STP Rotating Collection",
  "PS": "Preschool",
  "PT": "Preteen",
  "PR": "Professional Collection-Staff Only",
  "RD": "Reading Room",
  "RD2F": "Reading Room, 2nd Floor",
  "RF": "Reference",
  "RFST": "Reference Storage, Ask Staff for Help",
  "RFTB": "Reference Tables",
  "RF2F": "Reference, 2nd Floor",
  "RFLL": "REference, Lower Level",
  "RK": "Renk Room",
  "ABC": "Rotating Collection",
  "WEB": "See Online Resources",
  "SDY": "Serendipity",
  "SPA": "Spanish Language Collection",
  "SP": "Staff Picks",
  "ST": "Storage, Ask Staff for Help",
  "STY": "Storytime Room",
  "STU": "Studio",
  "TR": "Teacher Resources Collection",
  "TE": "Teen",
  "TEDISML": "Teen Display, Main Level",
  "TEIS": "Teen Islands",
  "TESE": "Teen Series",
  "TECH": "Teen's Choice Display",
  "TE1F": "Teen, 1st Floor",
  "TE2F": "Teen, 2nd Floor",
  "TEML": "Teen, Main Level",
  "TEST": "Test Guides",
  "TD": "Toddler",
  "TGTM": "Too Good Too Miss",
  "UNILL": "University on the Go, Lower Level",
  "WIS": "Wisconsin Collection",
  "YA": "Young Adult",
  "YADIS": "Young Adult Display",
  "YA2F": "Young Adult, 2nd Floor"
};

const collectionCodes = {
  "AR": "Art",
  "BAEJ": "Book/Audio-Enabled JU",
  "BCJ": "Book/Cassette JU",
  "BCDJ": "Book/CD JU",
  "BDAPJ": "Book/Digital Audio JU",
  "BKAFI": "Books AD FIC",
  "BKAFICN": "Books AD FIC Christian",
  "BKAFICL": "Books AD FIC Classics",
  "BKAFIFA": "Books AD FIC Fantasy",
  "BKAFIGN": "Books AD FIC Graphic Novels",
  "BKAFIHI": "Books AD FIC Historical",
  "BKAFIHL": "Books AD FIC Holiday",
  "BKAFIHO": "Books AD FIC Horror",
  "BKAFIIN": "Books AD FIC Inspirational",
  "BKAFIMY": "Books AD FIC Mystery",
  "BKAFIRO": "Books AD FIC Romance",
  "BKAFIID": "Books AD FIC SCID",
  "BKAFISF": "Books AD FIC Science Fiction",
  "BKAFISP": "Books AD FIC Spanish",
  "BKAFISL": "Books AD FIC Street Lit",
  "BKAFISU": "Books AD FIC Suspense",
  "BKAFITH": "Books AD FIC Thriller",
  "BKAFIUR": "Books AD FIC Urban",
  "BKAFIWE": "Books AD FIC Westerns",
  "BKAFIWL": "Books AD FIC World Language",
  "BKAGE": "Books AD Genealogy",
  "BKANF": "Books AD NFIC",
  "BKANFAR": "Books AD NFIC Art",
  "BKANFAU": "Books AD NFIC Autobiography",
  "BKANFBY": "Books AD NFIC Biography",
  "BKANFBU": "Books AD NFIC Business",
  "BKANFCK": "Books AD NFIC Cooking",
  "BKANFCR": "Books AD NFIC Crafts",
  "BKANFED": "Books AD NFIC Education",
  "BKANFGN": "Books AD NFIC Graphic Novels",
  "BKANFHE": "Books AD NFIC Health",
  "BKANFHS": "Books AD NFIC History",
  "BKANFHL": "Books AD NFIC Holiday",
  "BKANFHM": "Books AD NFIC Home",
  "BKANFHT": "Books AD NFIC Hot Topics",
  "BKANFJO": "Books AD NFIC Jobs/Career",
  "BKANFLM": "Books AD NFIC Local Materials",
  "BKANFPC": "Books AD NFIC Popular Culture",
  "BKANFRE": "Books AD NFIC Religion",
  "BKANFID": "Books AD NFIC SCID",
  "BKANFSC": "Books AD NFIC Science",
  "BKANFSH": "Books AD NFIC Self-Help",
  "BKANFSP": "Books AD NFIC Spanish",
  "BKANFSR": "Books AD NFIC Sports",
  "BKANFTL": "Books AD NFIC Travel",
  "BKANFWL": "Books AD NFIC World Language",
  "BKARN": "Books AD Rental",
  "BKJBG": "Books JU Big Books",
  "BKJFI": "Books JU FIC",
  "BKJFIAW": "Books JU FIC Award Winners",
  "BKJFIBE": "Books JU FIC Beginner",
  "BKJFIBI": "Books JU FIC Bilingual",
  "BKJFICH": "Books JU FIC Chapter",
  "BKJFICO": "Books JU FIC Comics",
  "BKJFIFA": "Books JU FIC Fantasy",
  "BKJFIGN": "Books JU FIC Graphic Novel",
  "BKJFIMY": "Books JU FIC Mystery",
  "BKJFI14": "Books JU FIC Primary (Gr. 1-4)",
  "BKJFISF": "Books JU FIC Science Fiction",
  "BKJFISP": "Books JU FIC Spanish",
  "BKJFIWL": "Books JU FIC World Language",
  "BKJHL": "Books JU Holiday",
  "BKJNF": "Books JU NFIC",
  "BKJNFBI": "Books JU NFIC Bilingual",
  "BKJNFBY": "Books JU NFIC Biography",
  "BKJNFGN": "Books JU NFIC Graphic Novel",
  "BKJNF14": "Books JU NFIC Primary (Gr. 1-4)",
  "BKJNFSP": "Books JU NFIC Spanish",
  "BKJNFWL": "Books JU NFIC World Language",
  "BKYFI": "Books YA FIC",
  "BKYFICL": "Books YA FIC Classics",
  "BKYFICO": "Books YA FIC Comics",
  "BKYFIFA": "Books YA FIC Fantasy",
  "BKYFIGN": "Books YA FIC Graphic Novel",
  "BKYFIGNMG": "Books YA FIC Graphic Novels (Manga)",
  "BKYFIMY": "Books YA FIC Mysteries",
  "BKYFISF": "Books YA FIC Science Fiction",
  "BKYFIWL": "Books YA FIC World Language",
  "BKYNF": "Books YA NFIC",
  "BKYNFGN": "Books YA NFIC Graphic Novel",
  "BKYNFWL": "Books YA NFIC World Language",
  "CAAFI": "Cassettes AD FIC",
  "CAAMS": "Cassettes AD Music",
  "CAANF": "Cassettes AD NFIC",
  "CAJ": "Cassettes JU",
  "CAY": "Cassettes YA",
  "CDAFI": "Compact Discs AD FIC",
  "CDAMD": "Compact Discs AD Music",
  "CDAMSID": "Compact Discs AD Music SCID",
  "CDANF": "Compact Discs AD NFIC",
  "CDAID": "Compact Discs AD SCID",
  "CDASP": "Compact Discs AD Spanish",
  "CDAWL": "Compact Discs AD World Language",
  "CDY": "Compact Discs YA",
  "DAPAFI": "Digital Audio AD FIC",
  "DAPANF": "Digital Audio AD NFIC",
  "DAPAID": "Digital Audio AD SCID",
  "DAPAWL": "Digital Audio AD World Language",
  "DAPJ": "Digital Audio JU",
  "DAPY": "Digital Audio YA",
  "DVDAAN": "DVD AD Anime",
  "DVDAFE": "DVD AD Feature",
  "DVDAFF": "DVD AD Foreign Feature",
  "DVDAHL": "DVD AD Holiday",
  "DVDANF": "DVD AD Non-Feature",
  "DVDARN": "DVD AD Rental",
  "DVDAID": "DVD AD SCID",
  "DVDATV": "DVD AD Television Shows",
  "DVDAWL": "DVD AD World Language",
  "DBRAAN": "DVD Blu-Ray AD Anime",
  "DBRAFE": "DVD Blu-Ray AD Feature",
  "DBRAFF": "DVD Blu-Ray AD Foreign Feature",
  "DBRANF": "DVD Blu-Ray AD Non-Feature",
  "DBRARN": "DVD Blu-Ray AD Rental",
  "DBRAID": "DVD Blu-Ray AD SCID",
  "DBRATV": "DVD Blu-Ray AD Television Shows",
  "DBRJ": "DVD Blu-Ray JU",
  "DVDJFE": "DVD JU Feature",
  "DVDJHL": "DVD JU Holiday",
  "DVDJNF": "DVD JU Non-Feature",
  "DVDJWL": "DVD JU World Language",
  "DVDYFE": "DVD YA Feature",
  "ERJFI": "Early Readers JU FIC",
  "ERJNF": "Early Readers JU NFIC",
  "ELR": "Electronic Resource",
  "ELRA": "Electronic Resource Audio",
  "ELRM": "Electronic Resource Music",
  "ELRV": "Electronic Resource Video",
  "EQ": "Equipment",
  "IL": "Interloan",
  "KTA": "Kits Adult",
  "KTJ": "Kits Juvenile",
  "LPFI": "Large Print FIC",
  "LPFIMY": "Large Print FIC Mysteries",
  "LPFIWE": "Large Print FIC Westerns",
  "LPNF": "Large Print NFIC",
  "LPPB": "Large Print Picture Books",
  "MAA": "Magazines AD",
  "MAAWL": "Magazines AD World Language",
  "MAJ": "Magazines JU",
  "MAY": "Magazines YA",
  "MPA": "Maps AD",
  "MF": "Microfilm",
  "PAAFI": "Paperbacks AD FIC",
  "PAAFICL": "Paperbacks AD FIC Classics",
  "PAAFIFA": "Paperbacks AD FIC Fantasy",
  "PAAFIMY": "Paperbacks AD FIC Mystery",
  "PAAFIRO": "Paperbacks AD FIC Romance",
  "PAAFISF": "Paperbacks AD FIC Science Fiction",
  "PAAFIWE": "Paperbacks AD FIC Western",
  "PAANF": "Paperbacks AD NFIC",
  "PAJFI": "Paperbacks JU FIC",
  "PAJNF": "Paperbacks JU NFIC",
  "PAYFI": "Paperbacks YA FIC",
  "PH": "Phonorecords",
  "PBJBBBI": "Picture Books JU Board Books Bilingual",
  "PBJCN": "Picture Books JU Concept",
  "PBJFI": "Picture Books JU FIC",
  "PBJFIBI": "Picture Books JU FIC Bilingual",
  "PBJFIBB": "Picture Books JU FIC Board Books",
  "PBJFIWL": "Picture Books JU FIC World Language",
  "PBJHL": "Picture Books JU Holiday",
  "PBJNF": "Picture Books JU NFIC",
  "SC": "Scores",
  "SEEDS": "Seeds",
  "SOA": "Software AD",
  "SOAWL": "Software AD World Language",
  "SOJ": "Software JU",
  "TY": "Toys",
  "VF": "Vertical File",
  "VGA": "Video Games AD",
  "VGJ": "Video Games JU",
  "VGY": "Video Games YA",
  "VRA": "Video REC AD",
  "VRJ": "Video REC JU"
};

const pbjfi = {
  "ADV": "Advanced",
  "ANI": "Animals",
  "CEL": "Celebration",
  "CHA": "Characters",
  "CON": "Concepts",
  "FAV": "Favorites",
  "FOL": "Folk",
  "GRO": "Growing",
  "NAT": "Nature",
  "RHY": "Rhymes",
  "STO": "Stories",
  "GO": "Things that Go"
};
